"""Coverage table: what the staged dataset contains, per competition and season.

Computed from the staged Parquet tables only, so docs/coverage.md always matches the data.
It holds counts, not StatsBomb data, so it can be committed.
"""

from pathlib import Path

import pandas as pd

COLUMNS = ["competition", "season", "matches", "events", "shots", "first_match", "last_match"]


def coverage(staged_dir: Path) -> pd.DataFrame:
    """Count matches, events and shots (penalty shootouts excluded) per competition season."""
    matches = pd.read_parquet(
        staged_dir / "matches.parquet", columns=["match_id", "competition", "season", "match_date"]
    )
    events = pd.read_parquet(staged_dir / "events.parquet", columns=["match_id"])
    shots = pd.read_parquet(staged_dir / "shots.parquet", columns=["match_id", "period"])
    shots = shots[shots.period < 5]  # shootout kicks are not match shots

    per_match = matches.set_index("match_id")
    per_match["events"] = events.match_id.value_counts()
    per_match["shots"] = shots.match_id.value_counts()
    per_match = per_match.fillna({"events": 0, "shots": 0})

    table = (
        per_match.groupby(["competition", "season"])
        .agg(
            matches=("match_date", "size"),
            events=("events", "sum"),
            shots=("shots", "sum"),
            first_match=("match_date", "min"),
            last_match=("match_date", "max"),
        )
        .reset_index()
        .astype({"matches": int, "events": int, "shots": int})
    )
    return table[COLUMNS].sort_values(["competition", "season"]).reset_index(drop=True)


def render_markdown(table: pd.DataFrame) -> str:
    lines = [
        "# Data coverage",
        "",
        "Generated by `uv run pitchlens coverage` from the staged tables; do not edit by hand.",
        "Shots exclude penalty shootouts (period 5). Data: StatsBomb open data.",
        "",
        "| Competition | Season | Matches | Events | Shots | First match | Last match |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in table.itertuples(index=False):
        lines.append("| " + " | ".join(str(value) for value in row) + " |")
    return "\n".join(lines) + "\n"
