"""Train xG v1 on the staged data and report the results (`pitchlens train`, `pitchlens evaluate`).

Outputs under models_dir (inside data/, never committed): the fitted pipeline, per-shot predictions
and a metadata file. `evaluate` writes docs/xg-v1-results.md (counts and metrics only, so it can be
committed) and a calibration plot under models_dir.
"""

import json
import pickle
from collections.abc import Collection
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")  # files only, no window; works the same on Windows and macOS
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

from pitchlens.xg import (  # noqa: E402
    calibration_table,
    evaluate,
    fit_xg,
    penalty_xg,
    predict_xg,
    split,
)

PREDICTIONS = "xg_v1_predictions.parquet"
METADATA = "xg_v1.json"
MODEL = "xg_v1.pkl"
CALIBRATION_PLOT = "xg_v1_calibration.png"


def train(staged_dir: Path, models_dir: Path, test_competitions: Collection[str]) -> dict[str, Any]:
    features = pd.read_parquet(staged_dir / "shot_features.parquet")
    sides = split(features, test_competitions)
    model = fit_xg(features[sides == "train"])

    predictions = features[["event_id", "match_id", "competition", "is_goal", "statsbomb_xg"]]
    predictions = predictions.assign(split=sides, xg=predict_xg(model, features))

    matches = pd.read_parquet(staged_dir / "matches.parquet", columns=["match_id", "competition"])
    shots = pd.read_parquet(staged_dir / "shots.parquet").merge(matches, on="match_id")
    train_competitions = sorted(set(matches.competition) - set(test_competitions))
    penalty_value, penalty_count = penalty_xg(shots, train_competitions)
    test_penalty_rate, test_penalty_count = penalty_xg(shots, test_competitions)

    metadata = {
        "train_competitions": train_competitions,
        "test_competitions": sorted(test_competitions),
        "model": "LogisticRegression(C=1.0, L2), scikit-learn",
        "feature_names": model.feature_names,
        "coefficients": model.coefficients,
        "intercept": model.intercept,
        "penalty_xg": penalty_value,
        "penalty_train_count": penalty_count,
        "penalty_test_count": test_penalty_count,
        "penalty_test_conversion": test_penalty_rate,
    }
    models_dir.mkdir(parents=True, exist_ok=True)
    predictions.to_parquet(models_dir / PREDICTIONS, index=False)
    (models_dir / MODEL).write_bytes(pickle.dumps(model.pipeline))
    (models_dir / METADATA).write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    return metadata


def _table(frame: pd.DataFrame, floats: str = "{:.4f}") -> list[str]:
    header = "| " + " | ".join(str(column) for column in frame.columns) + " |"
    lines = [header, "|" + "---|" * len(frame.columns)]
    for row in frame.itertuples(index=False):
        cells = [floats.format(v) if isinstance(v, float) else str(v) for v in row]
        lines.append("| " + " | ".join(cells) + " |")
    return lines


def results_markdown(predictions: pd.DataFrame, metadata: dict[str, Any]) -> str:
    test = predictions[predictions.split == "test"]
    data = (
        predictions.groupby(["split", "competition"])
        .agg(matches=("match_id", "nunique"), shots=("is_goal", "size"), goals=("is_goal", "sum"))
        .reset_index()
        .sort_values(["split", "competition"], ascending=[False, True])
    )
    coefficients = pd.DataFrame(
        {
            "feature": ["(intercept)", *metadata["feature_names"]],
            "coefficient": [metadata["intercept"], *metadata["coefficients"]],
        }
    )
    penalties = pd.DataFrame(
        {
            "set": ["train (penalty xG)", "test (observed)"],
            "penalties": [metadata["penalty_train_count"], metadata["penalty_test_count"]],
            "conversion": [metadata["penalty_xg"], metadata["penalty_test_conversion"]],
        }
    )
    goals = test.is_goal.to_numpy()
    lines = [
        "# xG v1 results",
        "",
        "Generated by `uv run pitchlens evaluate`; do not edit by hand. Data: StatsBomb open data.",
        "Shots exclude penalties (valued separately) and penalty shootouts. Metrics are on the",
        "test set only; lower log loss and Brier score are better.",
        "",
        f"Model: {metadata['model']}. Reference categories: body part `foot`, play type "
        "`open_play`.",
        "",
        "## Data and split",
        "",
        *_table(data),
        "",
        "## Test-set metrics",
        "",
        *_table(evaluate(predictions)),
        "",
        "## Coefficients",
        "",
        "Log-odds per unit (distance in metres, angle in radians, first_time 0/1, categories vs "
        "reference).",
        "",
        *_table(coefficients),
        "",
        "## Penalties",
        "",
        *_table(penalties),
        "",
    ]
    for name, column in [("PitchLens xG v1", "xg"), ("StatsBomb xG", "statsbomb_xg")]:
        table = calibration_table(test[column].to_numpy(), goals)
        table["bin"] = table["bin"].astype(str)
        lines += [f"## Calibration on the test set: {name}", "", *_table(table), ""]
    return "\n".join(lines)


def write_calibration_plot(predictions: pd.DataFrame, path: Path) -> None:
    test = predictions[predictions.split == "test"]
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.plot([0, 1], [0, 1], linestyle="--", color="grey", label="Perfect calibration")
    for name, column in [("PitchLens xG v1", "xg"), ("StatsBomb xG", "statsbomb_xg")]:
        table = calibration_table(test[column].to_numpy(), test.is_goal.to_numpy())
        ax.plot(table.mean_predicted, table.observed_rate, marker="o", label=name)
    ax.set_xlabel("Mean predicted xG in bin")
    ax.set_ylabel("Observed goal rate in bin")
    ax.set_title("xG v1 calibration, test set\nData: StatsBomb open data", fontsize=10)
    ax.legend()
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def write_results(models_dir: Path, output: Path) -> Path:
    predictions = pd.read_parquet(models_dir / PREDICTIONS)
    metadata = json.loads((models_dir / METADATA).read_text(encoding="utf-8"))
    output.write_text(results_markdown(predictions, metadata), encoding="utf-8", newline="\n")
    plot = models_dir / CALIBRATION_PLOT
    write_calibration_plot(predictions, plot)
    return plot
