[project]
name = "pitchlens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "João Meira", email = "150527324+JoaoMeira29@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.6",
    "matplotlib>=3.11.2",
    "mplsoccer>=1.8.1",
    "pandas>=3.0.6",
    "pandera>=0.34.1",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.1",
    "statsbombpy>=1.22.0",
    "typer>=0.27.2",
]

[project.scripts]
pitchlens = "pitchlens.cli:app"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
